name: CI Docker - Uvicorn Web App

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-scan-sign:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: uvicorn-web-app
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (local only)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: 'table'
          output: 'trivy-report.txt'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt

      # ------------ COSIGN --------------

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0

      - name: Write Cosign keys
        run: |
          echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
          echo "${{ secrets.COSIGN_PUBLIC_KEY }}" > cosign.pub
      
      - name: Cosign sign image (local)
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign sign --key cosign.key --local-image ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Cosign verify image (local)
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign verify --key cosign.pub --local-image ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}


      - name: Cosign sign image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          cosign sign --key cosign.key ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Cosign verify image
        run: |
          cosign verify --key cosign.pub ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

